# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples

export EDITOR=nvim || vim
export DOT13_INSTALLED="$HOME/dot13/.installed"

function dot13_installed() {
  test -f $DOT13_INSTALLED && grep -q $1 $DOT13_INSTALLED
}

function dot13_mark_installed() {
  touch $DOT13_INSTALLED
  (grep -q $1 $DOT13_INSTALLED && echo "[$1] already installed") ||
    echo $1 >> $DOT13_INSTALLED
}

function dot13_installed_or_mark() {
  if dot13_installed "$1"; then
    return 1
  else
    dot13_mark_installed "$1"
    return 0
  fi
}

# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

# don't put duplicate lines or lines starting with space in the history.
# See bash(1) for more options
HISTCONTROL=ignoreboth

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=1000
HISTFILESIZE=2000

# Load all functions
for config_file in $HOME/dot13/sh/functions/*; do
  source $config_file
done

# Load all configuration
for config_file in $HOME/dot13/sh/config/*; do
  source $config_file
done

# Load all initializers
for config_file in $HOME/dot13/sh/initializers/*; do
  source $config_file
done
