#!/bin/bash

if [ ! -d "$HOME/dot13" ]; then
    echo "Installing dot13"
    git clone https://github.com/ernestas-poskus/dot13.git "$HOME/dot13"
fi

echo "Linking dotfiles"

# Dot files
for f in $HOME/dot13/dotfiles/*; do
  if [ -f $f ]; then
    echo "ln -sf $f $HOME/.$(basename $f)"
    ln -sf $f "$HOME/.$(basename $f)"
  fi
done
