# Initialize zsh prezto
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Load all of your custom configurations from zsh/config
for config_file in $HOME/dot13/sh/config/*; do
  source $config_file
done

# Load all of your custom configurations from zsh/functions
for config_file in $HOME/dot13/sh/functions/*; do
  source $config_file
done
#
# Load all of initializers from zsh/initializers
for config_file in $HOME/dot13/sh/initializers/*; do
  source $config_file
done

# Report CPU usage for commands running longer than 10 seconds
REPORTTIME=10
