# Initialize zsh prezto
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Load all of your custom configurations from zsh/config
for config_file in $HOME/dot13/zsh/config/*; do
  source $config_file
done

# Load all of your custom configurations from zsh/functions
for config_file in $HOME/dot13/zsh/functions/*; do
  source $config_file
done
#
# Load all of initializers from zsh/initializers
for config_file in $HOME/dot13/zsh/initializers/*; do
  source $config_file
done
