#!/bin/bash

#Rust
export RUST_SRC_PATH="$HOME/.rsvm/current"

#dot13
DOT_PATH="$HOME/dot13"
DOT_PATH_INSTALL="$DOT_PATH/install"

export DOT_PATH="$DOT_PATH"
export DOT_PATH_INSTALL="$DOT_PATH_INSTALL"
export DOT_PATH_LINUX="$DOT_PATH/os/linux"
export DOT_PATH_DARWIN="$DOT_PATH/os/darwin"

if [ $(uname -s) = 'Darwin' ]; then
  export DOT13_ENV="work"
else
  export DOT13_ENV="home"
  export LANG=en_US.UTF-8
  export LANGUAGE=en_US.UTF-8
  export LC_COLLATE=C
  export LC_CTYPE=en_US.UTF-8
fi
